apiVersion: apps/v1
kind: Deployment
metadata:
  name: housing-disrepair
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: housing-disrepair
  template:
    metadata:
      labels:
        app: housing-disrepair
    spec:
      containers:
        - name: webapp
          ports:
            - containerPort: 3000
          command: ['docker run --rm -it -p 3000:3000 $(docker build -q .)']
